version: "3"

services:
  webserver:
    image: "webserver:0.02"
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - '80:80'
    links:
      - mariadb
    volumes:
      - ../html:/var/www/html:z
      - ../secrets:/var/www/secrets:z
      - ./scripts:/var/www/scripts:z
      - ./logs:/var/www/logs:z
  mariadb:
    image: "mariadb:latest"
    restart: unless-stopped
    volumes: 
      - database-volume:/var/lib/mysql
    env_file:
      - ../secrets/variables.env
    ports:
      - '3306:3306'
  phpmyadmin:
    image: "phpmyadmin:5.1.0-apache"
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    volumes:
      - ./logs:/logging:z
    environment:
      - PMA_HOST=mariadb
volumes:
  database-volume: